# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    container_name: backend-dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://admin:password@db:5432/dev'
      DIRECT_URL: 'postgresql://admin:password@db:5432/dev'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    command: npm run start:migrate:dev
    depends_on:
      - redis
      - db

  db:
    image: postgres:16.3
    restart: always
    container_name: db-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - dev-db:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    restart: always
    container_name: redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  dev-db:
