# Use this file to run a local development server.
# Example usage: docker-compose up -d -V --build

version: '3.9'

services:
  lumberjacked:
    build:
      dockerfile: DockerfileLocal
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    container_name: lumberjacked-local
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://admin:password@postgres:5432/local'
      DIRECT_URL: 'postgresql://admin:password@postgres:5432/local'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    command: npm run start:migrate:dev
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:16.3-alpine
    restart: always
    container_name: postgres-local
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    volumes:
      - local-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis-local
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  local-db:
